version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    env_file:
      - .env
    # override env_file with environment variables from docker-compose.yml
    environment:
      - PYTHON_PATH=/usr/bin/python3
      - RAILS_ENV=development
      - POSTGRES_HOST=postgres
      - MONGO_URL=mongodb://mongo:27017/yt_development
      - MEMCACHED_URL=memcached:11211
    depends_on:
      - postgres
      - mongo
      - memcached
    networks:
      - app-network

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

volumes:
  postgres_data:
  mongo_data:
  bundle:

networks:
  app-network:
    driver: bridge