version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=postgres
      - MONGODB_URI=mongodb://mongodb:27017/yt_development
    depends_on:
      - postgres
      - mongodb
    networks:
      - app-network

  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  postgres_data:
  mongodb_data:
  bundle_cache:
  node_modules:

networks:
  app-network:
    driver: bridge