development:
  clients:
    default:
      uri: mongodb://localhost:27017/yt_development
      options:
        server_selection_timeout: 5

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        server_selection_timeout: 5